"""CJ O-NE 배송조회 통합구성요소 상수."""

DOMAIN = "cj_one_delivery"

CONF_AUTH_CODE = "auth_code"
CONF_ACCESS_TOKEN = "access_token"
CONF_PHONE_NUMBER = "phone_number"
CONF_REFRESH_TOKEN = "refresh_token"
CONF_USER_ID = "user_id"
CONF_SCAN_INTERVAL_MINUTES = "scan_interval_minutes"
CONF_COMPLETED_RETENTION_DAYS = "completed_retention_days"

DEFAULT_SCAN_INTERVAL_MINUTES = 30
MIN_SCAN_INTERVAL_MINUTES = 5
MAX_SCAN_INTERVAL_MINUTES = 180
DEFAULT_COMPLETED_RETENTION_DAYS = 7
MIN_COMPLETED_RETENTION_DAYS = 1
MAX_COMPLETED_RETENTION_DAYS = 90

PLATFORMS = ["sensor"]
